Add calendar app
AbstractSDK/abstract pull request #100
Opened 2023-10-16 23:28 UTC by AndrewPochapsky

### Overview
This PR adds the calendar-app originally created [here](https://github.com/AndrewPochapsky/abstract-calendar-module) to this repo. The main difference between the two versions is that this one fixes the mistake of sending funds to the admin instead of the proxy when slashing. There is more test coverage that we can add to account for all of the possible cases which I am happy to work on if that is a priority. 

### Checklist

- [ ] CI is green.
- [ ] Changelog updated.

2023-10-17 09:10 UTC, CyberHoward commented on modules/contracts/apps/calendar/README.md
Could you give this an update? It will be used on the FE to explain what the application does and how it can be used. Also helps us maintain it.

2023-10-17 09:18 UTC, CyberHoward commented on modules/contracts/apps/calendar/src/msg.rs
> +pub enum AppExecuteMsg {
Could you add doc-comments to the fields of these variants? 

What's day_datetime and why is it a signed int?

2023-10-17 16:20 UTC, Buckram123 requested changes
Very cool app, few small nits and g2g. Love the tests by the way, ultra-clean!
Error variant names feels a little too long, what do you think?

One more thing to discuss: do we want to have addrs "whitelist"? Or we just allow anyone throw their tokens to to your "calendar", and potentially troll real meetings? They will pay for it, so it's kind of whatever, but still

2023-10-18 00:05 UTC, AndrewPochapsky commented on modules/contracts/apps/calendar/src/handlers/execute.rs
> +    });
Good idea, thanks :)

2023-10-18 00:05 UTC, AndrewPochapsky commented on modules/contracts/apps/calendar/src/handlers/execute.rs
> +    let timezone: FixedOffset = FixedOffset::east_opt(config.utc_offset).unwrap();
Good catch, I had missed this.

2023-10-18 00:06 UTC, AndrewPochapsky commented on modules/contracts/apps/calendar/README.md
> +```
I honestly just used the croncat readme as a guide so this might not apply in this case.

2023-10-18 00:12 UTC, AndrewPochapsky commented on modules/contracts/apps/calendar/src/handlers/execute.rs
> +    }
I totally agree, the current implementation was chosen for simplicity for a proof of concept. A "proper" implementation which allows cross-day meetings would be a bit tricky, though do-able of course. I suggest we add that as an enhancement in a future PR if that is something we want to prioritize which would keep this PR simpler and also make that change easier to review if we choose to include it. What do you think?

2023-10-18 00:21 UTC, AndrewPochapsky commented
> Very cool app, few small nits and g2g. Love the tests by the way, ultra-clean! Error variant names feels a little too long, what do you think?

Ha yeah the names are kind of long. I shortened two of the longest ones and am happy to try to shorten some others too. If this goes against the usual convention used by the team please let me know!


> One more thing to discuss: do we want to have addrs "whitelist"? Or we just allow anyone throw their tokens to to your "calendar", and potentially troll real meetings? They will pay for it, so it's kind of whatever, but still


Might make sense  to have an allow-list, or maybe even like a one-time allow-list where the owner gives someone a single opportunity to schedule a meeting. In theory though if spam is a problem the owner can just raise the price-per-minute to make it not worth it.

2023-10-19 11:12 UTC, Buckram123 approved these changes
LGTM!
Few last non-critical things:

1. @CyberHoward recently slapped
```rust
#![warn(missing_docs)]
```
into every `msg.rs`, which helped documenting every messages we have.

2. `config.utc_offset` is not checked during instantiation, and is not configurable, which can make this contract unusable after instantiation.

For future upgrade: it could be pretty useful to have configuration of the offset for folks that travels often. Not sure how to achieve it tho :rofl:

2023-10-19 17:43 UTC, CyberHoward commented on modules/contracts/apps/calendar/README.md
> +```
Yeah probably not. We'll give all the readmes a nice review once we have them live and working!

2023-10-20 09:37 UTC, CyberHoward commented
> ## [Codecov](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK) Report
> > Merging [#100](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK) ([51eb5a8](https://github.com/AbstractSDK/abstract/commit/51eb5a814ff37cfd51464c738cad1a9b2c8e5c81)) into [main](https://app.codecov.io/gh/AbstractSDK/abstract/commit/7c9c262eaf23b74f18a553829e3bbc7448676b96?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK) ([7c9c262](https://github.com/AbstractSDK/abstract/commit/7c9c262eaf23b74f18a553829e3bbc7448676b96)) will **increase** coverage by `20.1%`.
> > Report is 165 commits behind head on main.
> > The diff coverage is `49.9%`.
> 
> [Files](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK)	Coverage Δ	
> [framework/contracts/account/manager/src/error.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9hY2NvdW50L21hbmFnZXIvc3JjL2Vycm9yLnJz)	`0.0% <ø> (ø)`	
> [framework/contracts/account/proxy/src/contract.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9hY2NvdW50L3Byb3h5L3NyYy9jb250cmFjdC5ycw==)	`60.7% <100.0%> (+19.6%)`	⬆️
> [framework/contracts/account/proxy/src/queries.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9hY2NvdW50L3Byb3h5L3NyYy9xdWVyaWVzLnJz)	`44.5% <ø> (+44.5%)`	⬆️
> [...work/contracts/native/account-factory/src/error.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9uYXRpdmUvYWNjb3VudC1mYWN0b3J5L3NyYy9lcnJvci5ycw==)	`0.0% <ø> (ø)`	
> [framework/contracts/native/ans-host/src/queries.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9uYXRpdmUvYW5zLWhvc3Qvc3JjL3F1ZXJpZXMucnM=)	`3.9% <ø> (ø)`	
> [...work/contracts/native/version-control/src/error.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL2NvbnRyYWN0cy9uYXRpdmUvdmVyc2lvbi1jb250cm9sL3NyYy9lcnJvci5ycw==)	`25.0% <ø> (ø)`	
> [...packages/abstract-adapter/src/endpoints/execute.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL3BhY2thZ2VzL2Fic3RyYWN0LWFkYXB0ZXIvc3JjL2VuZHBvaW50cy9leGVjdXRlLnJz)	`55.9% <ø> (ø)`	
> [...ages/abstract-adapter/src/endpoints/instantiate.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL3BhY2thZ2VzL2Fic3RyYWN0LWFkYXB0ZXIvc3JjL2VuZHBvaW50cy9pbnN0YW50aWF0ZS5ycw==)	`100.0% <100.0%> (ø)`	
> [...ramework/packages/abstract-adapter/src/features.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL3BhY2thZ2VzL2Fic3RyYWN0LWFkYXB0ZXIvc3JjL2ZlYXR1cmVzLnJz)	`50.0% <100.0%> (ø)`	
> [framework/packages/abstract-adapter/src/state.rs](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK#diff-ZnJhbWV3b3JrL3BhY2thZ2VzL2Fic3RyYWN0LWFkYXB0ZXIvc3JjL3N0YXRlLnJz)	`5.5% <ø> (ø)`	
> ... and [80 more](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK)		
> ... and [142 files with indirect coverage changes](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK)

@AndrewPochapsky so seems like the action works! 

One thing I noticed a while back is that the reports seem off. See:

"Merging [#100](https://app.codecov.io/gh/AbstractSDK/abstract/pull/100?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK) (https://github.com/AbstractSDK/abstract/commit/51eb5a814ff37cfd51464c738cad1a9b2c8e5c81) into [main](https://app.codecov.io/gh/AbstractSDK/abstract/commit/7c9c262eaf23b74f18a553829e3bbc7448676b96?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AbstractSDK) (https://github.com/AbstractSDK/abstract/commit/7c9c262eaf23b74f18a553829e3bbc7448676b96) will increase coverage by 20.1%."

A **20%** increase? This is why I was bugging you about if there's a way to split it up or whatever because all of our reports used to give these kind of numbers. 

And if you have a look at the [actual report](https://app.codecov.io/gh/AbstractSDK/abstract/tree/calendar-app/framework%2Fcontracts%2Faccount%2Fmanager%2Fsrc) you see that the coverage is (seemingly) very low for the framework contracts. 

So this shows that the module coverage report is also adding coverage to the framework workspace, which IMO it shouldn't (or it should be merged).

Thoughts?

Related to #102

2023-10-20 09:40 UTC, CyberHoward approved these changes
LGTM!!

2023-10-20 12:51 UTC, merged