App admin verification
AbstractSDK/abstract pull request #160
Opened 2023-11-23 12:59 UTC by Buckram123

This PR aims to give top-level account owner admin privileges on apps
### Checklist

- [ ] CI is green.
- [x] Changelog updated.

2023-11-23 13:30 UTC, CyberHoward approved these changes
This is 🔥

2023-11-23 15:07 UTC, CyberHoward commented
Should we do this for Adapters as well? For the whitelist config?

2023-11-24 13:21 UTC, Buckram123 commented
> Should we do this for Adapters as well? For the whitelist config?

Sure, updated!

2023-11-27 09:20 UTC, CyberHoward requested changes

2023-11-28 14:24 UTC, CyberHoward approved these changes
Great change!

2023-11-28 14:26 UTC, Buckram123 commented on framework/packages/abstract-core/src/core/manager.rs
> +pub const MAX_MANAGER_ADMIN_RECURSION: usize = 2;
Not sure about it, since it's directly depend on managers to be admins of sub-accounts chain

2023-11-28 14:39 UTC, Buckram123 commented on framework/packages/abstract-core/src/core/manager.rs
> +pub const MAX_MANAGER_ADMIN_RECURSION: usize = 2;
Ok, moved and renamed it. Comment of what type of admin recursion is that should be hopefully enough

2023-11-28 17:07 UTC, merged